name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and pushing changes
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # Add environment variables for Supabase
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: List directory contents
        run: ls -la
        
      - name: Install dependencies and update lock file
        run: |
          echo "Installing dependencies and updating package-lock.json..."
          npm install
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package-lock.json
          git commit -m "Update package-lock.json" || echo "No changes to commit"
          git push || echo "No changes to push"
        
      - name: Build with Next.js
        run: |
          echo "Starting build..."
          echo "Using Supabase URL: ${NEXT_PUBLIC_SUPABASE_URL:-Not set}"
          # Don't print the actual key, just check if it exists
          if [ -n "$NEXT_PUBLIC_SUPABASE_ANON_KEY" ]; then
            echo "Supabase anon key is set"
          else
            echo "Supabase anon key is NOT set"
          fi
          npm run build
          echo "Build completed"
          echo "Contents of out directory:"
          ls -la out/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 